debugging

diff --git a/.github/workflows/deploy.production.yml b/.github/workflows/deploy.production.yml
--- a/.github/workflows/deploy.production.yml
+++ b/.github/workflows/deploy.production.yml
@@ -44,10 +44,36 @@ jobs:
             ${{ runner.os }}-pnpm-store-
       - name: Install Dependencies
         run: pnpm install --frozen-lockfile
-      - name: Setup tmate session
-        uses: mxschmitt/action-tmate@v3
-        with:
-          limit-access-to-actor: true
+      - name: Create a new tag
+        id: create_tag
+        run: |
+          echo "Fetching the latest tag..."
+          LATEST_TAG=$(git tag --sort=-creatordate | grep 'production-v' | head -1)
+          echo "Latest tag: ${LATEST_TAG}"
+          echo "Extracting version number from the latest tag..."
+          VERSION_NUMBER=$(echo ${LATEST_TAG} | grep -o -E '[0-9]+')
+          echo "Version number: ${VERSION_NUMBER}"
+          if [ -z "$VERSION_NUMBER" ]; then
+            echo "No version number found. Setting it to 0..."
+            VERSION_NUMBER=0
+          fi
+          echo "Incrementing the version number..."
+          NEW_VERSION_NUMBER=$((VERSION_NUMBER + 1))
+          echo "New version number: ${NEW_VERSION_NUMBER}"
+          NEW_TAG="production-v${NEW_VERSION_NUMBER}"
+          echo "New tag: ${NEW_TAG}"
+          echo "Writing new tag to GITHUB_OUTPUT..."
+          echo "new_tag=${NEW_TAG}" >> "$GITHUB_OUTPUT"
+          if [ $? -ne 0 ]; then
+            echo "Failed to write new tag to GITHUB_OUTPUT"
+            exit 1
+          fi
+      - name: Push the new tag
+        run: |
+          git config user.name "GitHub Actions"
+          git config user.email "github-actions@users.noreply.github.com"
+          git tag ${{ steps.create_tag.outputs.new_tag }}
+          git push origin ${{ steps.create_tag.outputs.new_tag }}
       - name: Compile Wing Cloud dependencies
         run: npx turbo compile --filter=!@wingcloud/infrastructure
       - name: Compile Wing Cloud
@@ -74,20 +100,6 @@ jobs:
           TF_BACKEND_STATE_FILE: "${{ github.repository }}/production-${{ github.run_id }}/infrastructure/main.tfstate"
         run: pnpm wing compile -t tf-aws main.w --platform s3.backend.js
         working-directory: "apps/@wingcloud/infrastructure"
-      - name: Create a new tag
-        id: create_tag
-        run: |
-          LATEST_TAG=$(git tag --sort=-creatordate | grep 'production-v' | head -1)
-          VERSION_NUMBER=$(echo ${LATEST_TAG} | grep -o -E '[0-9]+')
-          NEW_VERSION_NUMBER=$((VERSION_NUMBER + 1))
-          NEW_TAG="production-v${NEW_VERSION_NUMBER}"
-          echo "new_tag=${NEW_TAG}" >> "$GITHUB_OUTPUT"
-      - name: Push the new tag
-        run: |
-          git config user.name "GitHub Actions"
-          git config user.email "github-actions@users.noreply.github.com"
-          git tag ${{ steps.create_tag.outputs.new_tag }}
-          git push origin ${{ steps.create_tag.outputs.new_tag }}
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
